update

diff --git a/bash/bin/search_engine/search_engine b/bash/bin/search_engine/search_engine
--- a/bash/bin/search_engine/search_engine
+++ b/bash/bin/search_engine/search_engine
@@ -15,28 +15,23 @@
 # Example:
 #   gnu_alias # => you use use sed
 #######################################
-function gnu_alias {
-  # include gurad.
-  # if you set alias, return.
-  if [ ! -z $GNU_ALIAS ]; then
-    return
-  fi
-  # you use Darwin, set alias for use Gnu sed, awk, xargs
-  if uname | grep -e Darwin -e BSD > /dev/null; then
-    if ! gnu_exists; then
-      echo "Any Gnu command is not exists." >&2
-      return 1
-    fi
-    # 環境変数 SEDを作ってマッピングして後で消すという方法もある。
-    alias sed=gsed
-    alias awk=gawk
-    alias xargs=gxargs
-    alias find=gfind
-    alias date=gdate
-    alias cut=gcut
+function search_engine {
 
-    export GNU_ALIAS=GNU_ALIAS
+  local filepath=$(realpath $(dirname $0))
+
+  local search_engine=$1
+  if [ -z $search_engine ]; then
+    echo "assign search_engine value!" >&2
+    return 1
   fi
+  local engine=$(jq -r .${search_engine} ${filepath}/search_engin.json)
+
+  if [ "null" = "$engine" ]; then
+    echo "cannot find you specify search engine!" >&2
+    return 1
+  fi
+
+  echo $engine
 }
 
 function main {
@@ -57,7 +52,7 @@ function main {
   # reindex assign.
   new_array=${new_array[@]}
 
-  gnu_alias $new_array
+  search_engine $new_array
 }
 
 main $@
diff --git a/bash/bin/url_encode b/bash/bin/url_encode
--- a/bash/bin/url_encode
+++ b/bash/bin/url_encode
@@ -1,31 +1,31 @@
 #!/bin/bash
 #
-# Comment, .env, file utils
+# gnu command util.
 
 #######################################
-# cat 
+# write stderr syntax. google style(https://google.github.io/styleguide/shellguide.html)
 # Globals:
-#   None
+#   LOGFORMAT
 # Arguments:
-#   Stdout to delete comment ,a path. this param 
+#   All.
 # Outputs:
-#   Writes lines delete file_header.
+#   format 
 # Returns:
-#   0 if thing was deleted, non-zero on error.
+#   0 if thing was set alias, non-zero on error.
 # Example:
-#   cat file | file_exists
-#   file_exists file
+#   url_encode "Unable to do_something"  # => you use use sed
 #######################################
-function file_exists {
+function url_encode() {
+  local sentense=$1
 
-  # $@がなかったら - を取るというふうに作る必要がある。
-  local filepath
-  for filepath in $@; do
-    if ! [ -e $filepath ]; then
-      echo "${filepath} is not exists." >&2
-      return 1
-    fi
-  done
+  if ! type "nkf" > /dev/null; then
+    echo "nkf is not exists. install nkf!" >&2
+    return 1
+  fi
+
+  echo $sentense | \
+    nkf -WwMQ | \
+    sed 's/=/%/g'
 }
 
 function main {
@@ -46,7 +46,7 @@ function main {
   # reindex assign.
   new_array=${new_array[@]}
 
-  file_exists $new_array
+  url_encode $new_array
 }
 
 main $@
