update

diff --git a/bash/bin/test_expect b/bash/bin/test_expect
--- a/bash/bin/test_expect
+++ b/bash/bin/test_expect
@@ -3,6 +3,62 @@
 # gnu command util.
 
 #######################################
+# select menu items
+# Globals:
+#   PS3
+#   REPLY
+# Arguments:
+#   PS3 variable
+#   after args menu items.
+# Outputs:
+#   None
+# Returns:
+#   0 if select exists menu, non-zero on error occured.
+# Example:
+#   $ select_menu 'your like cooking' hamburger curry sushi
+#   1) hamburger
+#   2) curry
+#   3) sushi
+#   your like cooking. Enter 'q' for cancel. > 1
+#   $ if "${?}" != 0; then
+#   >   echo 'error occured select_menu function.' >&2
+#   >   return 1 
+#   > fi
+#   $ if "${REPLY}" = 'q'; then
+#   >   echo 'user cancel' 
+#   >   return
+#   > fi
+#   $ echo $REPLY 
+#######################################
+function select_menu {
+  # check input select message
+  if [ -z $1 ]; then
+    echo 'input select message!' >&2
+    return 1
+  fi
+  PS3="${1} Enter 'q' for cancel. > "
+  # args after two index, assined menu variable.
+  local menu=(${@:2:($#-1)})
+  if [ -z $menu ]; then
+    echo 'set variable for select menu' >&2
+    return 1
+  fi
+  # loop for select menu.
+  local item
+  select item in "${menu[@]}"
+  do
+    if [ "${REPLY}" = "q" ]; then
+      return
+    fi
+    # break loop for select existing menu.
+    if [ -z $item ]; then
+      break
+    fi
+    echo "invalid selection. choose select menu" >&2
+  done
+}
+
+#######################################
 # write stderr syntax. google style(https://google.github.io/styleguide/shellguide.html)
 # Globals:
 #   LOGFORMAT
@@ -15,16 +71,7 @@
 # Example:
 #   url_encode "Unable to do_something"  # => you use use sed
 #######################################
-function md2epub() {
-
-        #   'pandoc','-f','markdown'
-        # ,'-t', 'epub3'
-        # ,path.join(self.setting.target, self.setting.manuscript)
-        # ,path.join(self.setting.target, self.setting.title)
-        # ,'-o', path.join(self.setting.target, self.setting.out)
-        # ,'--css', path.join(self.setting.target, self.setting.css)
-        # ,'--toc', '--toc-depth=2'
-        # ,'--epub-cover-image={}'.format(path.join(self.setting.target, self.setting.cover_image))
+function text_expect() {
 
   local i
   local title
@@ -77,33 +124,11 @@ function md2epub() {
     --epub-cover-image=$cover
 }
 
-function usage() {
-    cat 1>&2 <<EOF
-search_engine
-output search engine setting
-
-USAGE:
-    search_engine [FLAGS] [OPTIONS]
-
-FLAGS:
-    -l, --list              Show usable search engines.
-    -d, --detail            Show search engine detail
-    -h, --help              Prints help information
-
-OPTIONS:
-    --debug                 Set bash debug Option
-EOF
-}
-
 function main {
 
   local i
   local new_array=( $@ )
   for ((i=0;i<$#;i++)); do
-    if [ "${new_array[$i]}" = "--help" ] || [ "${new_array[$i]}" = "-h" ]; then
-      usage()
-      return
-    fi
     # if find --debug flag from args, start debug mode.
     if [ "${new_array[$i]}" = "--debug" ]; then
       set -x
